config/routes.rb
Rails.application.routes.draw do
  resources :excursions
  resources :teachers 
  resources :articles 
  resources :students
  get '/', to: 'main#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # resources :teachers do
  #   collection do
  #     get 'displayart'
  #   end
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, :description, :teacher_id, presence: true

    belongs_to :teacher
    has_many :excursions
    has_many :students, through: :excursions
end

app/models/excursion.rb
class Excursion < ApplicationRecord
    belongs_to :student 
    belongs_to :article
end

app/models/student.rb
class Student < ApplicationRecord
    validates :name, presence: true

    has_many :excursions
    has_many :articles, through: :excursions
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    validates :name, presence: true

    has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
        @excursion = Excursion.new
    end

    def create
        
        @article = Article.new(article_params)
        @article.save
        # @excursion = Excursion.new(article_id: @article.id, excursion_date: params[:article][:article_date])
        # @excursion.save
        redirect_to article_path(@article)
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        @article.update(article_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to '/articles/new', :notice => "Your article has been deleted"
    end
    def displayart
        @display = Article.where("teacher_id = ?", @teacher.id)
    end

private 
    def article_params
        params.require(:article).permit(:name, :description, :teacher_id)
    end
end

app/controllers/excursions_controller.rb
class ExcursionsController < ApplicationController
    def index
        @excursions = Excursion.all
    end
    
    def new
        @excursion = Excursion.new
    end

    def create
        @excursion = Excursion.new(
            article_id: params[:excursion][:article_id],
            student_id: params[:excursion][:student_id],
            excursion_date: params[:excursion][:excursion_date]
            )
        @excursion.save
        
    end

    def show
        @excursion = Excursion.find(params[:id])
    end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        render "homepage"
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        @students = Student.all
    end

    def show
        @student = Student.find(params[:id])
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        @student.save
        redirect_to student_path(@student)
    end

    def edit
        @student = Student.find(params[:id])
    end

    def update
        @student = Student.find(params[:id])
        @student.update(student_params)
        redirect_to student_path(@student)
    end

    

private 
    def student_params
        params.require(:student).permit(:name, article_id: [])
    end

    # def create
    #     @student = Student.new(student_params)
    #     @student.save
    #     redirect_to student_path(@student)
    # end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def index
        @teachers = Teacher.all
    end

    def show
        @teacher = Teacher.find(params[:id])
    end

    def new
        @teacher = Teacher.new
    end


    def create
        @teacher = Teacher.new(teacher_params)
        @teacher.save
        redirect_to teacher_path(@teacher)
    end

    def edit
        @teacher = Teacher.find(params[:id])
    end

    def update
        @teacher = Teacher.find(params[:id])
        @teacher.update(teacher_params)
        redirect_to teacher_path(@teacher)
    end

    def displayart
        @display = Article.where("teacher_id = ?", @teacher.id)
    end

private 
    def teacher_params
        params.require(:teacher).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/excursions_helper.rb
module ExcursionsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/articles/edit.html.erb
<div class='main'>
<h2>Update Article Form</h2>

<%= form_for @article do |f| %>
<label>Name : </label><br>
<%= f.text_field :name %><br>

<label>Description   : </label><br>
<%= f.text_field :description %><br>

<label>Which teacher was there ?  : </label><br>
<%= f.text_field :teacher_id %><br>

<%= f.submit 'Update Article' %>

<%end%>
</div>

app/views/articles/index.html.erb
<div class='main'>
<% @articles.each do |article| %>
<h1><%= link_to article.name, article_path(article)%></h1>

<% end %>
<button> <%= link_to "Create a new article", "/articles/new" %> </button>
</div>

app/views/articles/new.html.erb
<div class='main'>
<h2>New Article Form</h2>

<%= form_for @article do |f| %>
<label>Name : </label><br>
<%= f.text_field :name %><br>

<label>Description : </label><br>
<%= f.text_field :description %><br>

<label>Teacher who was at the excursion : </label><br>
<%= f.text_field :teacher_id %><br>

<%= f.submit 'Create Article' %>
<% end %>

</div>

app/views/articles/show.html.erb
<div class='main'>
<h1><%= @article.name %></h1>

<h2><%= @article.description %></h2>
<h2>Teacher present at the excursion :  </h2>
<h2>- <%= Teacher.find_by(id: @article.teacher_id).name %>, id : <%= Teacher.find_by(id: @article.teacher_id).article_id %></h2>

<button><%= link_to 'Back', :back %></button>
</div>

app/views/excursions/index.html.erb
<div class='main'>
<% @excursions.each do |excursion| %>
<h1><%= link_to "#{excursion.article.name} | #{excursion.excursion_date}", excursion_path(excursion)%></h1>

<% end %>
<button> <%= link_to "Create a new excursion", "/excursions/new" %> </button>
</div>

app/views/excursions/new.html.erb
<div class='main'>
<h2>New excursion Form</h2>

<%= form_for @excursion do |f| %>
<label>Article id : </label><br>
<%= f.text_field :article_id %><br>


<label>Student id : </label><br>
<%= f.text_field :student_id %><br>

<label>Excursion date : </label><br>
<%= f.time_field :excursion_date %><br>



<%= f.submit 'Create excursion' %>

<%end%>
</div>

app/views/excursions/show.html.erb
<div class='main'>
<h1><%= "#{@excursion.student.name} | #{@excursion.excursion_date}" %></h1>

<button><%= link_to 'Edit', edit_excursion_path %></button>
<button><%= link_to 'Back', :back %></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipeapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/homepage.html.erb
<h1> Welcome on Recipeapp  </h1>

<button> <%= link_to "Students", "/students" %> </button>
<button> <%= link_to "Teachers", "/teachers" %> </button>
<button> <%= link_to "Articles", "/articles" %> </button>
<button> <%= link_to "Excursions", "/excursions" %> </button>

app/views/students/edit.html.erb
<div class='main'><h2>Update Student Form</h2>

<%= form_for @student do |f| %>
<label>Name : </label><br>
<%= f.text_field :name %><br>




<%= f.submit 'Update Student' %>

<%end%>
</div>

app/views/students/index.html.erb
<div class='main'>
<% @students.each do |student| %>
<h1><%= link_to student.name, student_path(student)%></h1>

<% end %>
<button> <%= link_to "Create a new student", "/students/new" %> </button>
</div>

app/views/students/new.html.erb
<div class='main'>
<h2>New Student Form</h2>

<%= form_for @student do |f| %>
<label>Name : </label><br>
<%= f.text_field :name %><br>

<%= f.submit 'Create Student' %>

<%end%>
</div>
<%# <h2>New Student Form</h2> %>
<%# %>
<%# <%= form_for @student do |f| %>
<%# <label>Name : </label><br>%>
<%# <%= f.text_field :name %>
<%# %>
<%# <label>in Which excursion @student.name was there ? : </label><br>%>
<%# <%= f.input_field :article_id %>
<%# %>
<%# <%= f.submit 'Create Student' %> 
<%# %>
<%# <%end%>

app/views/students/show.html.erb
<div class='main'>
<h1><%= @student.name %></h1>
<h2><% @student.excursions %></h2>
<h2><%= "Which excursion(s) #{@student.name} have done ?" %> </h2><br>

<% if @student.excursions.length > 0 %>
<% @student.excursions.each do |x|  %><br>
<% Article.where("id = ?", x.article_id).each do |article| %><br>
<h4><ul>
   <li> <%= article.name %> </li> 
   </ul></h4>
<% end %>
<% end %>
<% else %>
<h4> <%=  "#{@student.name} hasn't done any excursion yet !" %> </h4>
<% end %>

<button><%= link_to 'Edit', edit_student_path %></button>
<button><%= link_to 'Back', :back %></button>
</div>

app/views/teachers/edit.html.erb
<div class='main'>
<h2>Update Teacher Form</h2>

<%= form_for @teacher do |f| %>
<label>Name : </label><br>
<%= f.text_field :name %><br>

<label>Article id  : </label><br>
<%= f.text_field :article_id %><br>

<%= f.submit 'Update Teacher' %>

<%end%>
</div>

app/views/teachers/index.html.erb
<div class='main'>
<% @teachers.each do |teacher| %>
<h1><%= link_to teacher.name, teacher_path(teacher)%></h1>

<% end %>
<button> <%= link_to "Create a new teacher", "/teachers/new" %> </button>
</div>

app/views/teachers/new.html.erb
<div class='main'>
<h2>New Teacher Form</h2>

<%= form_for @teacher do |f| %>
<label>Name : </label><br>
<%= f.text_field :name %><br>


<%= f.submit 'Create Teacher' %>

<%end%>
</div>

app/views/teachers/show.html.erb
<div class='main'>
<h1><%= @teacher.name %></h1>
<h2><%= "in Which excursions #{@teacher.name} went ?" %></h2>

<% if Article.where("teacher_id = ?", @teacher.id).length > 0  %>
<% Article.where("teacher_id = ?", @teacher.id).each do |excursion| %>
<h4><ul>
   <li> <%= excursion.name %> </li> 
   </ul></h4>
  <% end %>
  <% else %>
  <h4> <%=  "#{@teacher.name} hasn't done any excursion yet !" %> </h4>
  <% end %>

<button><%= link_to 'Back', :back %></button>
</div>